require("my-config.globals")
require("my-config.settings")
require("my-config.mappings")
require("my-config.lsp-config")
require("my-config.lazy")
require("my-config.autocommands")
require("my-config.filetype-specifics")
