local leader = ";"

vim.g.VM_default_mappings = 0
vim.g.VM_mouse_mappings = 1

vim.g.VM_maps = {
    ["Find Under"]         = "<C-n>",
    ["Find Subword Under"] = "<C-n>",
    ["Add Cursor Down"]    = "<A-J>",
    ["Add Cursor Up"]      = "<A-K>",
    ["Switch Mode"]        = "<Tab>",
    ["Find Prev"]          = "[",
    ["Find Next"]          = "]",
    ["Goto Next"]          = "}",
    ["Goto Prev"]          = "{",
    ["Seek Next"]          = "<C-f>",
    ["Seek Prev"]          = "<C-b>",
    ["Skip Region"]        = "q",
    ["Remove Region"]      = "Q",
    ["Invert Direction"]   = "o",
    ["Find Operator"]      = "m",
    ["Surround"]           = "S",
    ["Replace Pattern"]    = "R",

    ["Select All"]           = leader .. "A",
    ["Start Regex Search"]   = leader .. "/",
    ["Add Cursor At Pos"]    = leader .. "\\",
    ["Visual Regex"]         = leader .. "r",
    ["Visual All"]           = leader .. "A",
    ["Visual Add"]           = leader .. "a",
    ["Visual Find"]          = leader .. "f",
    ["Visual Cursors"]       = leader .. "c",
    ["Tools Menu"]           = leader .. "T",
    ["Show Registers"]       = leader .. "R",
    ["Case Setting"]         = leader .. "c",
    ["Toggle Whole Word"]    = leader .. "w",
    ["Transpose"]            = leader .. "t",
    ["Align"]                = leader .. "a",
    ["Duplicate"]            = leader .. "d",
    ["Rewrite Last Search"]  = leader .. "r",
    ["Merge Regions"]        = leader .. "m",
    ["Split Regions"]        = leader .. "s",
    ["Remove Last Region"]   = leader .. "q",
    ["Visual Subtract"]      = leader .. "s",
    ["Case Conversion Menu"] = leader .. "C",
    ["Search Menu"]          = leader .. "S",
    ["Run Normal"]           = leader .. "z",
    ["Run Last Normal"]      = leader .. "Z",
    ["Run Visual"]           = leader .. "v",
    ["Run Last Visual"]      = leader .. "V",
    ["Run Ex"]               = leader .. "x",
    ["Run Last Ex"]          = leader .. "X",
    ["Run Macro"]            = leader .. "@",
    ["Align Char"]           = leader .. "<",
    ["Align Regex"]          = leader .. ">",
    ["Numbers"]              = leader .. "n",
    ["Numbers Append"]       = leader .. "N",
    ["Zero Numbers"]         = leader .. "0n",
    ["Zero Numbers Append"]  = leader .. "0N",
    ["Shrink"]               = leader .. "-",
    ["Enlarge"]              = leader .. "+",
    ["Toggle Block"]         = leader .. "<BS>",
    ["Toggle Single Region"] = leader .. "<CR>",
    ["Toggle Multiline"]     = leader .. "M",
}

-- Mouse mappings
vim.keymap.set("n", "<C-LeftMouse>", "<Plug>(VM-Mouse-Cursor)")
vim.keymap.set("n", "<C-RightMouse>", "<Plug>(VM-Mouse-Word)  ")
vim.keymap.set("n", "<M-C-RightMouse>", "<Plug>(VM-Mouse-Column)")
